Repository natasha-codes/snek, pull requests merged in 2019-11, with the labels that each got.

#3 Add test CI action
  .github/workflows/build_and_test.yml
  src/snek/foo.rs
Labels: infra

#6 Add `.rustfmt.toml` config
  .rustfmt.toml
  src/main.rs
Labels: infra

#10 Add style action
  .github/workflows/style.yml
  src/snek/foo.rs
Labels: infra

#12 Use `--verbose` `cargo fmt` flag
  .github/workflows/style.yml
Labels: infra

#13 Add automerge action
  .github/workflows/automerge.yml
Labels: automerge, infra

#11 Use `cargo check` not `cargo build`
  .github/workflows/check_and_test.yml
Labels: automerge, infra

#19 Add CODEOWNERS file to make @nathan and @sasha global code owners
  .github/CODEOWNERS
Labels: automerge, infra

#14 Fix shellcheck lints
  .githooks/pre-commit
  bin/setup-dev.sh
  bin/shellcheck.sh
Labels: infra

#22 Add shellcheck action
  .github/workflows/shellcheck.yml
Labels: wip

#23 Remove automerge action
  .github/workflows/automerge.yml
Labels: infra
